git:
  depth: 1
branches:
  except:
    - /(?i:appveyor)/
language: c++
compiler:
  - gcc
  - clang
os: osx
matrix:
  include:
    - osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && EXTRA_BREW= && DYLD_LIBRARY_PATH=":/usr/local/opt/wxmac/lib/:/usr/local/Cellar/jack/0.125.0_2/lib:-L/usr/local/lib"

    - osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++ && EXTRA_BREW=gcc && DYLD_LIBRARY_PATH=":/usr/local/opt/wxmac/lib/:/usr/local/Cellar/jack/0.125.0_2/lib:-L/usr/local/lib"




before_install:
    - mkdir -p config lib/rtmidi/config
    - touch config/config.rpath lib/rtmidi/config/config.rpath
    - eval "${MATRIX_EVAL}"
    - pwd
    - ls
    - if test "$TRAVIS_OS_NAME" = osx ; then  brew update ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew upgrade boost ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi # fix broken gcc installation

script:
    - if test "$TRAVIS_OS_NAME" = osx ; then echo "DYLD_LIBRARY_PATH = $DYLD_LIBRARY_PATH" ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then echo "DYLD_FALLBACK_FRAMEWORK_PATH = $DYLD_FALLBACK_FRAMEWORK_PATH" ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then make install &&  make tests ; fi ;
